name: Cppcheck

on:
  push:
    branches: [ master ]
    paths:
    - .github/workflows/cppcheck.yml
    - '**.[ch]'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install cppcheck
      run: sudo apt-get install -qq cppcheck
    - name: Run cppcheck
      run: >
        cppcheck
        --quiet
        --force
        --enable=all
        --error-exitcode=1
        -UENABLE_THREADS
        --suppress=ctunullpointer:libircclient/src/colors.c:49
        --suppress=invalidLifetime:libircclient/src/libircclient.c:666
        --suppress=invalidLifetime:libircclient/src/libircclient.c:703
        --suppress=nullPointerRedundantCheck:libircclient/src/libircclient.c:567
        --suppress=unusedFunction:libircclient/src/*.c
        .