name: NASA's IKOS Analyzer

on:
  push:
    branches: [ master ]
    paths:
    - .github/workflows/ikos.yml
    - '**.[ch]'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    container: ghcr.io/mario-campos/ikos-dockerfile:3.0-4
    steps:
    - name: Install dependencies
      run: apt-get install -qq libbsd-dev
      
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run IKOS
      run: ikos -D_FILE_OFFSET_BITS=64 -DLIBBSD_OVERLAY -I/usr/include/bsd xdccget.c
      
    - name: Show IKOS findings
      run: ikos-report output.db
